demo_app:
    resource: '../Controller/'
    type: attribute

demo_logout:
    path: /logout

admin_area:
    resource: '@AdminataBundle/Resources/config/routing/adminata.php'
    prefix: /admin

_adminata_admin:
    resource: .
    type: adminata
    prefix: /admin
