"""
Sphinx configuration for the adminata documentation.

One site out of the seven that came with the forked packages: `admin-bundle` first, then the
five that support it, each under its own section. Upstream's file was generated by
`sonata-project/dev-kit` and carried a "DO NOT EDIT" banner; this one is written by hand,
because the fork's documentation is not generated by anything.

`nitpicky` is deliberate. The build is part of CI, and a warning is an error, so a cross-reference
that stops resolving when a page is pruned fails the build rather than shipping a dead link.
"""

from pygments.lexers.web import PhpLexer
from sphinx.highlighting import lexers

project = 'adminata'
copyright = '2026, IDCT Bartosz Pachołek; 2010-2025 Thomas Rabaix and the Sonata contributors'
author = 'IDCT Bartosz Pachołek'

extensions = ['sphinx_rtd_theme']
templates_path = ['_templates']
# `_*.rst` are include fragments, not pages, so they are not part of any toctree.
exclude_patterns = ['_build', 'requirements.txt', '_*.rst', '**/_*.rst']

# PHP without an opening tag is the norm in these pages, and it is what upstream configured.
highlight_language = 'php'

for name in ('php', 'php-annotations', 'php-attributes', 'php-standalone', 'php-symfony'):
    lexers[name] = PhpLexer(startinline=True)

html_theme = 'sphinx_rtd_theme'
html_static_path = ['_static']
html_title = 'adminata'
htmlhelp_basename = 'adminata'

# Every `:doc:` and `:ref:` has to resolve.
nitpicky = True
